- build: examples/simple
  photon: [0.7.0, 1.0.0, 1.1.1, 1.3.1, 1.4.0]
  p1: [latest]
  electron: [0.7.0, 1.0.0, 1.1.1, 1.3.1, 1.4.0]
  argon: [0.9.0, 1.1.1, 1.3.1, 1.4.0]
  boron: [latest]
  xenon: [latest]
